#!/bin/bash
set -euo pipefail

EXEC_DIR="${EXEC_DIR:-$(pwd)}"
: "${AUGMENTATION_PLAN_DIR:?Set AUGMENTATION_PLAN_DIR}"
: "${AUGMENTATION_RUN_ROOT:?Set AUGMENTATION_RUN_ROOT}"
: "${AUGMENTATION_AUDIT_DIR:?Set AUGMENTATION_AUDIT_DIR}"
: "${PARENT_COLLECTION_PLAN_DIR:?Set PARENT_COLLECTION_PLAN_DIR}"
: "${PARENT_COLLECTION_RUN_ROOT:?Set PARENT_COLLECTION_RUN_ROOT}"
: "${BASE_SOURCE_DIR:?Set BASE_SOURCE_DIR}"
: "${PARENT_GRAPH_DATASET_DIR:?Set PARENT_GRAPH_DATASET_DIR}"
: "${SCALABLE_DATASET_DIR:?Set SCALABLE_DATASET_DIR}"

TASKS=$(wc -l < "${AUGMENTATION_PLAN_DIR}/scalable_augmentation_tasks.jsonl")
if [[ "${TASKS}" -le 0 ]]; then
    echo "[ERROR] augmentation task manifest is empty" >&2
    exit 2
fi
MAX_PARALLEL_TASKS="${MAX_PARALLEL_TASKS:-2}"
EXPORTS="ALL,EXEC_DIR=${EXEC_DIR},AUGMENTATION_PLAN_DIR=${AUGMENTATION_PLAN_DIR}"
EXPORTS+=",AUGMENTATION_RUN_ROOT=${AUGMENTATION_RUN_ROOT}"
EXPORTS+=",PARENT_COLLECTION_RUN_ROOT=${PARENT_COLLECTION_RUN_ROOT}"
EXPORTS+=",BASE_SOURCE_DIR=${BASE_SOURCE_DIR}"

AUGMENTATION_JOB_ID=$(sbatch --parsable \
    --array="0-$((TASKS - 1))%${MAX_PARALLEL_TASKS}" \
    --export="${EXPORTS}" \
    scripts/slurm/dasci/submit_scalable_augmentation_task.sbs)
AUGMENTATION_JOB_ID=${AUGMENTATION_JOB_ID%%;*}

PARENT_GRAPH_JOB_ID=$(sbatch --parsable \
    --export="ALL,EXEC_DIR=${EXEC_DIR},PARENT_COLLECTION_PLAN_DIR=${PARENT_COLLECTION_PLAN_DIR},PARENT_COLLECTION_RUN_ROOT=${PARENT_COLLECTION_RUN_ROOT},BASE_SOURCE_DIR=${BASE_SOURCE_DIR},GUROBI_GRAPH_OUTPUT_DIR=${PARENT_GRAPH_DATASET_DIR}" \
    scripts/slurm/dasci/submit_gurobi_graph_dataset.sbs)
PARENT_GRAPH_JOB_ID=${PARENT_GRAPH_JOB_ID%%;*}

AUDIT_JOB_ID=$(sbatch --parsable \
    --dependency="afterok:${AUGMENTATION_JOB_ID}" \
    --export="ALL,EXEC_DIR=${EXEC_DIR},AUGMENTATION_PLAN_DIR=${AUGMENTATION_PLAN_DIR},AUGMENTATION_RUN_ROOT=${AUGMENTATION_RUN_ROOT},AUGMENTATION_AUDIT_DIR=${AUGMENTATION_AUDIT_DIR}" \
    scripts/slurm/dasci/submit_scalable_augmentation_audit.sbs)
AUDIT_JOB_ID=${AUDIT_JOB_ID%%;*}

DATASET_JOB_ID=$(sbatch --parsable \
    --dependency="afterok:${AUDIT_JOB_ID}:${PARENT_GRAPH_JOB_ID}" \
    --export="ALL,EXEC_DIR=${EXEC_DIR},AUGMENTATION_AUDIT_DIR=${AUGMENTATION_AUDIT_DIR},AUGMENTATION_RUN_ROOT=${AUGMENTATION_RUN_ROOT},PARENT_GRAPH_DATASET_DIR=${PARENT_GRAPH_DATASET_DIR},PARENT_COLLECTION_PLAN_DIR=${PARENT_COLLECTION_PLAN_DIR},PARENT_COLLECTION_RUN_ROOT=${PARENT_COLLECTION_RUN_ROOT},SCALABLE_DATASET_DIR=${SCALABLE_DATASET_DIR},ALLOW_PARTIAL_SMOKE=${ALLOW_PARTIAL_SMOKE:-0}" \
    scripts/slurm/dasci/submit_scalable_gurobi_dataset.sbs)
DATASET_JOB_ID=${DATASET_JOB_ID%%;*}

printf 'AUGMENTATION_JOB_ID=%s\n' "${AUGMENTATION_JOB_ID}"
printf 'PARENT_GRAPH_JOB_ID=%s\n' "${PARENT_GRAPH_JOB_ID}"
printf 'AUDIT_JOB_ID=%s\n' "${AUDIT_JOB_ID}"
printf 'DATASET_JOB_ID=%s\n' "${DATASET_JOB_ID}"
